# Generated by Django 6.1 on 2026-08-17 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_type', models.CharField(choices=[('SE', 'Самозанятый'), ('IP', 'ИП'), ('OOO', 'ООО')], max_length=3)),
                ('name', models.CharField(max_length=255, verbose_name='Название бренда')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН/ОГРНИП')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPSEDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=300, verbose_name='Фамилия')),
                ('passport_data', models.TextField(verbose_name='Паспортные данные')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ipse_details', to='brands.brandprofile')),
            ],
            options={
                'verbose_name': 'Реквизиты ИП/Самозанятого',
                'verbose_name_plural': 'Реквизиты ИП/Самозанятых',
            },
        ),
        migrations.CreateModel(
            name='OOODetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='Полное наименование организации')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('legal_address', models.TextField(verbose_name='Юридический адрес')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ooo_details', to='brands.brandprofile')),
            ],
            options={
                'verbose_name': 'Реквизиты ООО',
                'verbose_name_plural': 'Реквизиты ООО',
            },
        ),
    ]
